inputs:
  filebeat:
    host: :7200
    ssl_key: filebeat.key
    ssl_crt: filebeat.crt
outputs:
  tcp:
    host: :7201
  websocket:
     host: :7202
  elasticsearch:
    hosts:
      - http://localhost:9200
    index: "logstash"
    index_type: "logzoom"
    gzip_enabled: false
    info_log_enabled: false
    error_log_enabled: false
